-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 14:44:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` INT(9) NOT NULL,
  `pst_phone` BIGINT NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(6,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` INT(9) NOT NULL,
  `cus_phone` BIGINT NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(6,2) NOT NULL,
  `cus_total_sales` DECIMAL(6,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT NOT NULL,
  `cus_id` SMALLINT NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` DECIMAL(6,2) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(45) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `pst_id_idx` (`pst_id` ASC) VISIBLE,
  INDEX `cus_id_idx` (`cus_id` ASC) VISIBLE,
  CONSTRAINT `pst_id`
    FOREIGN KEY (`pst_id`)
    REFERENCES `mydb`.`petstore` (`pst_id`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT,
  CONSTRAINT `cus_id`
    FOREIGN KEY (`cus_id`)
    REFERENCES `mydb`.`customer` (`cus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (101, 'Bob\'s Pets', '123 Hi Lo St', 'Tallahassee', 'FL', 32313, 2345678901, 'petstore1@gmail.com', 'petstore1.com', 50.0, NULL);
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (102, 'Bobby\'s Pets', '123 Happy St', 'Tallahassee', 'FL', 32314, 1234567890, 'petstore2@gmail.com', 'petstore2.com', 100.0, NULL);
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (103, 'Pets R Us', '2525 W Tennessee St', 'Tallahassee', 'FL', 32354, 5612435678, 'petstore3@gmail.com', 'petstore3.com', 100.0, 'great store');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (104, 'Pets And Stuff', '5050 Pensacola St', 'Tallahassee', 'FL', 32313, 8506445364, 'petstore4@gmail.com', 'petstore4.com', 250.0, NULL);
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (105, 'Pets and Beyond', '123 Happy Ln', 'Miami', 'FL', 34215, 3056271827, 'petstore5@gmail.com', 'petstore5.com', 300.0, NULL);
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (106, 'Mark\'s Pets', '123 Happy Rd', 'Miami', 'FL', 21342, 7865243672, 'petstore6@gmail.com', 'petstore6.com', 300.0, '');
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (107, 'Petco', '3456 Congress Ave', 'Orlando', 'FL', 34256, 4079485948, 'petstore7@gmail.com', 'petstore7.com', 300.0, NULL);
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (108, 'Petsmart', '2781 S Militart Trl', 'Orlando', 'FL', 37261, 4078192938, 'petstore8@gmail.com', 'petstore8.com', 50.0, NULL);
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (109, 'Pets Pets Pets!', '3567 Via Valencia', 'Orlando', 'FL', 37281, 4078596830, 'petstore9@gmail.com', 'petstore9.com', 250.0, NULL);
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (110, 'Pets For Less', '8273 W Call St', 'Orlando', 'FL', 28172, 4071625362, 'petstore10@gmail.com', 'petstore10.com', 450.5, NULL);
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, '', DEFAULT, '', '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, NULL);
INSERT INTO `mydb`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, DEFAULT, DEFAULT, DEFAULT, '', DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (301, 'Mary', 'Trail', '234 Happy St', 'Tallahassee', 'FL', 32313, 8506442222, 'customer1@gmail.com', 25.25, 1000.00, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (302, 'Todd', 'Hall', '235 Happy St', 'Tallahassee', 'FL', 32313, 8506442223, 'customer2@.gmail.com', 50.50, 1000.00, 'they spent a lot of money');
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (303, 'Marie', 'Price', '236 Happy St', 'Tallahassee', 'FL', 32313, 8506442224, 'customer3@gmail.com', 100.54, 1000.00, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (304, 'Tori', 'Boudreau', '327 Sad St', 'Tallahassee', 'FL', 32313, 8506442225, 'customer4@gmail.com', 4503.34, 1000.00, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (305, 'Cameron', 'Callahan', '328 Sad St', 'Tallahassee', 'FL', 32313, 8506442226, 'customer5@gmail.com', 3000.23, 1000.00, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (306, 'Connor', 'Cajigal', '8737 Via Pinnacle', 'Tallahassee', 'FL', 32313, 8506442227, 'customer6@gmail.com', 548.98, 1000.00, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (307, 'Eli', 'Hay', '83920 Lament Way', 'Tallahassee', 'FL', 32313, 8506442228, 'customer7@gmail.com', 234.23, 1000.00, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (308, 'Matthew', 'Gonzalez', '3828 Happy Way', 'Tallahassee', 'FL', 32313, 8506442229, 'customer8@gmail.com', 1000.00, 1000.00, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (309, 'Kiera', 'Rendon', '8738 Via Juneau', 'Tallahassee', 'FL', 32313, 8506442230, 'customer9@gmail.com', 23.54, 1000.00, NULL);
INSERT INTO `mydb`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `pst_notes`) VALUES (310, 'Nathen', 'Mergen', '8373 College Ave', 'Tallahassee', 'FL', 32313, 8506442231, 'customer10@gmail.com', 3.01, 1000.00, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (201, 101, 301, 'dog', 'm', 200, 100, 5, 'black', '2015-12-17', 'y', 'n', 'awesome dog');
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (202, 102, 302, 'dog', 'm', 500, 1000, 5, 'white', '2015-12-17', 'y', 'n', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (203, 103, 303, 'dog', 'f', 800, 1000, 5, 'gray', '2015-12-17', 'y', 'n', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (204, 104, NULL, 'cat', 'f', 30, 50, 5, 'blue', '2015-12-17', 'y', 'n', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (205, 105, NULL, 'cat', 'f', 500, 555, 5, 'yellow', '2015-12-17', 'y', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (206, 106, NULL, 'cat', 'f', 25, 50, 5, 'blue', '2015-12-17', 'n', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (207, 107, 307, 'lizard', 'f', 10, 20, 5, 'teal', '2015-12-17', 'y', 'y', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (208, 108, 308, 'snake', 'f', 400, 800, 5, 'magenta', '2015-12-17', 'y', 'n', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (209, 109, 309, 'guinea pig', 'f', 5, 10, 5, 'orange', '2015-12-17', 'y', 'n', NULL);
INSERT INTO `mydb`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (210, 110, NULL, 'hamster', 'f', 10, 20, 5, 'white', '2015-12-17', 'y', 'n', NULL);

COMMIT;

